### ISSUE TITLE
upload.py authentication error

### ISSUE THREAD

**Issue by ldang** [socallinuxexpo/scale-av-cutter#22]
When running the `upload.py` without a valid credentials.json -- the authenication process craps out with the following.

```
Cannot find token file at credentials.json, starting authentication process
Traceback (most recent call last):
  File "./upload.py.orig", line 173, in <module>
    main()
  File "./upload.py.orig", line 131, in main
    credentials = obtain_credentials_from_flow(args.client)
  File "./upload.py.orig", line 35, in obtain_credentials_from_flow
    flow.run_console()
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'
```

Here are the versions of the google libraries that ended up being installed

```
google-api-core==2.11.0
google-api-python-client==2.81.0
google-auth==2.16.2
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
googleapis-common-protos==1.58.0
```

My work around was to replace this line:

`    flow.run_console()`

With this line:
`     flow.run_local_server(port=0)`

**Comment by ldang** [comment]
This issue is no longer a problem, and was probably fixed in the course of other issues filed against this repo.
